// Content-contract test for the session-end concern capture: the file-concerns
// process skill and the Stop hook that names it. Node built-ins only; zero token
// cost. Run: node tests/session-end-concerns.test.mjs
//
// The invariants here are the ones a well-meaning edit silently breaks. The hook
// prompt must stay phrased as a CONDITION — the harness wraps it as "has the
// following stopping condition been satisfied?", so an imperative is evaluated as
// though it were a condition and produces nonsense (observed: an imperative block
// reason produced "Understood, I'll do that IF I'm about to stop", i.e. the agent
// logged the rule instead of acting on it). It must keep its anti-nag clause,
// because every block replaces the session's closing message with hook-loop
// chatter. And it must keep naming the skill: the block `reason` is generated by
// the evaluator, not authored here, so without the name it has no procedure to
// point at.
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const ROOT = new URL('../', import.meta.url)
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

const tests = []
const test = (name, fn) => tests.push([name, fn])

test('file-concerns: exists as a process skill', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(/^---[\s\S]*?\ndescription:\s*\S.*\n[\s\S]*?---/m.test(md), 'frontmatter has a non-empty description')
  assert.ok(md.includes('name: file-concerns'), 'frontmatter name matches the directory')
  // Without this the skill is classified as a Workflow wrapper and breaks the
  // 1:1 workflow<->skill invariant in plugin-integrity.
  assert.ok(/^workflow:\s*none$/m.test(md), 'declares workflow: none (process skill, not a wrapper)')
  assert.ok(!md.includes('scriptPath'), 'must not masquerade as a Workflow wrapper')
})

test('file-concerns: files one issue per session to the agreed sink', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(md.includes('gh issue create -R schmug/agent-notes'), 'names the exact sink command')
  assert.ok(md.includes('--label concern'), 'labels the issue so triage can find it')
  assert.match(md, /one issue per session/i, 'states the one-issue-per-session rule')
  // Five issues out of one session is what the question board produced on
  // 2026-08-29 and it is the wrong shape for review.
  assert.ok(!/one issue per concern/i.test(md), 'must not file per concern')
})

test('file-concerns: never fails the turn', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(md.includes('~/.claude/concerns-spool.jsonl'), 'names the spool path')
  assert.match(md, /do not retry/i, 'forbids in-session retry')
  assert.match(md, /never.*(block|fail).*turn/i, 'states the never-fail-the-turn guarantee')
})

const hooksJson = JSON.parse(await read('hooks/hooks.json'))
const stopEntries = [].concat(hooksJson.hooks?.Stop || []).flatMap((g) => [].concat(g.hooks || []))

test('stop hook: one prompt-type entry with a timeout', () => {
  // Each entry costs a model call on every stop of every session.
  assert.equal(stopEntries.length, 1, 'exactly one Stop entry')
  // The agent type also runs on Stop and has tools, but costs ~13-16s per evaluation
  // against ~2-4s, and its tools are denied by default in unattended "don't ask" mode —
  // which is exactly where this capture matters most. See design spec section 2.
  assert.equal(stopEntries[0].type, 'prompt', 'is a prompt hook, not an agent hook')
  assert.ok(typeof stopEntries[0].timeout === 'number' && stopEntries[0].timeout > 0, 'sets a timeout')
})

test('stop hook: the prompt is phrased as a condition, not an instruction', () => {
  const p = stopEntries[0].prompt || ''
  // The harness wraps this as "has the following stopping condition been satisfied?".
  // An imperative is evaluated as though it were a condition and produces nonsense —
  // observed: an imperative reason produced "Understood, I'll reply with BANANA IF I'm
  // about to stop", i.e. the agent logged the rule instead of acting on it.
  assert.ok(p.startsWith('Either this session surfaced nothing unresolved'),
    'opens as a condition on the transcript')
})

test('stop hook: keeps the anti-nag clause, the skill name, and the escape hatch', () => {
  const p = stopEntries[0].prompt || ''
  // Every block replaces the session's closing message with hook-loop chatter, so a
  // hook that blocks routine sessions is destructive, not merely slow.
  assert.ok(p.includes('Default to satisfied'), 'keeps the anti-nag clause')
  // The block reason is generated by the evaluator, not authored here. Without the
  // skill name it has no procedure to point at.
  assert.ok(p.includes('shipofclaudius:file-concerns'), 'names the skill that does the filing')
  // What terminates the loop when gh is down: a spooled concern satisfies the condition.
  assert.ok(p.includes('concerns-spool.jsonl'), 'counts a spooled concern as satisfying it')
})

// ---- runner ----
let failed = 0
for (const [name, fn] of tests) {
  try { await fn(); console.log(`PASS ${name}`) }
  catch (e) { failed++; console.error(`FAIL ${name}\n  ${e.message}`) }
}
console.log(failed ? `\n${failed} failed` : `\nall ${tests.length} passed`)
process.exit(failed ? 1 : 0)
