// Content-contract test for the session-end concern capture: the file-concerns
// process skill and the Stop hook that names it. Node built-ins only; zero token
// cost. Run: node tests/session-end-concerns.test.mjs
//
// The invariants here are the ones a well-meaning edit silently breaks. The hook
// prompt must stay phrased as a CONDITION — the harness wraps it as "has the
// following stopping condition been satisfied?", so an imperative is evaluated as
// though it were a condition and produces nonsense (observed: an imperative block
// reason produced "Understood, I'll do that IF I'm about to stop", i.e. the agent
// logged the rule instead of acting on it). It must keep its anti-nag clause,
// because every block replaces the session's closing message with hook-loop
// chatter. And it must keep naming the skill: the block `reason` is generated by
// the evaluator, not authored here, so without the name it has no procedure to
// point at.
import { readFile, mkdtemp } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import assert from 'node:assert/strict'

const ROOT = new URL('../', import.meta.url)
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

const tests = []
const test = (name, fn) => tests.push([name, fn])

test('file-concerns: exists as a process skill', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(/^---[\s\S]*?\ndescription:\s*\S.*\n[\s\S]*?---/m.test(md), 'frontmatter has a non-empty description')
  // Anchored: `name: file-concerns-v2` in skills/file-concerns/ satisfied a bare
  // substring check, so the assertion passed on the exact name/directory mismatch that
  // breaks `shipofclaudius:file-concerns` resolution from the hook.
  assert.match(md, /^name: file-concerns$/m, 'frontmatter name matches the directory')
  // Without this the skill is classified as a Workflow wrapper and breaks the
  // 1:1 workflow<->skill invariant in plugin-integrity.
  assert.ok(/^workflow:\s*none$/m.test(md), 'declares workflow: none (process skill, not a wrapper)')
  assert.ok(!md.includes('scriptPath'), 'must not masquerade as a Workflow wrapper')
})

test('file-concerns: files one issue per session to the agreed sink', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  // Flag long/short forms both accepted — a rewrite to `--repo` or `-l` is not a defect.
  assert.match(md, /gh issue create[\s\S]{0,160}(-R|--repo) schmug\/agent-notes/, 'names the exact sink command')
  assert.match(md, /(--label|-l) concern/, 'labels the issue so triage can find it')
  // Pins the rule TOGETHER WITH its negation clause. A bare /one issue per session/
  // plus a hardcoded negative lookalike passed a body reading "Never one issue per
  // session — file one per concern instead", i.e. the exact inversion it guarded.
  // Five issues out of one session is what the question board produced on 2026-08-29.
  assert.match(md, /\*\*One issue per session\*\*\s*—\s*never one per concern/i,
    'states the one-issue-per-session rule, un-inverted')
})

test('file-concerns: never fails the turn', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.match(md, /(~|\$HOME)\/\.claude\/concerns-spool\.jsonl/, 'names the spool path')
  assert.match(md, /(do not|never) retry/i, 'forbids in-session retry')
  // Scoped to ONE clause. The old /never.*(block|fail).*turn/ needed only those words in
  // that order somewhere on a line, so it passed "Never let a lost concern pass silently:
  // block and fail the turn" — the precise inversion of the guarantee it names.
  // `[^.]*` rather than `[^.\n]*` so a paragraph reflow does not red CI.
  assert.match(md, /never (block|fail)[^.]*turn/i, 'states the never-fail-the-turn guarantee')
})

// `jq` is required to run the spool writers themselves. Absent it, the execution tests below
// cannot run -- skip rather than fail, so a bare dev box does not redden CI-green code.
let HAVE_JQ = true
try { execFileSync('sh', ['-c', 'command -v jq'], { stdio: 'ignore' }) } catch { HAVE_JQ = false }
let HAVE_GIT = true
try { execFileSync('sh', ['-c', 'command -v git'], { stdio: 'ignore' }) } catch { HAVE_GIT = false }

// Pulls every fenced `jq -nc ...` snippet out of the skill in document order: [0] is the
// concerns writer, [1] is the retraction writer (§4.5 of the design spec).
async function spoolWriters () {
  const md = await read('skills/file-concerns/SKILL.md')
  return [...md.matchAll(/```bash\n(jq -nc[\s\S]*?)\n```/g)].map((m) => m[1])
}

test('file-concerns: exactly two spool writers, concerns and retraction, with no crossed fields', async () => {
  const [concernsSnippet, retractSnippet] = await spoolWriters()
  assert.ok(concernsSnippet && retractSnippet, 'both spool-writer snippets are present')
  for (const field of ['ts', 'session', 'cwd', 'repo', 'concerns']) {
    assert.match(concernsSnippet, new RegExp(`\\b${field}:`), `concerns writer sets ${field}`)
  }
  assert.doesNotMatch(concernsSnippet, /\bretracts:/, 'concerns writer does not also emit retracts')
  for (const field of ['ts', 'session', 'cwd', 'repo', 'retracts']) {
    assert.match(retractSnippet, new RegExp(`\\b${field}:`), `retraction writer sets ${field}`)
  }
  assert.doesNotMatch(retractSnippet, /\bconcerns:/, 'retraction writer does not also emit concerns')
})

test('file-concerns: skill and spec agree field-for-field on both envelopes', async () => {
  const specDoc = await read('docs/specs/2026-08-30-session-end-concerns-design.md')
  assert.match(specDoc,
    /\{"ts":"<ISO8601>","session":"<id>","cwd":"<path>","repo":"<owner\/name\|null>","concerns":\["…"\]\}/,
    'spec states the concerns envelope verbatim, in ts/session/cwd/repo/concerns order')
  assert.match(specDoc,
    /\{"ts":"<ISO8601>","session":"<id>","cwd":"<path>","repo":"<owner\/name\|null>","retracts":\["…"\]\}/,
    'spec states the retraction envelope verbatim, in ts/session/cwd/repo/retracts order')
  const [concernsSnippet, retractSnippet] = await spoolWriters()
  assert.match(concernsSnippet,
    /\{ts:\$ts,session:\$session,cwd:\$cwd,repo:\(if \$repo=="" then null else \$repo end\),concerns:\$ARGS\.positional\}/,
    'concerns writer builds the object in the same ts/session/cwd/repo/concerns order as the spec')
  assert.match(retractSnippet,
    /\{ts:\$ts,session:\$session,cwd:\$cwd,repo:\(if \$repo=="" then null else \$repo end\),retracts:\$ARGS\.positional\}/,
    'retraction writer builds the object in the same ts/session/cwd/repo/retracts order as the spec')
})

test('file-concerns: the concerns writer really emits the five-field envelope', async () => {
  if (!HAVE_JQ) return console.log('  (skipped: jq not installed)')
  const [concernsSnippet] = await spoolWriters()
  const dir = await mkdtemp(join(tmpdir(), 'file-concerns-'))
  const spool = join(dir, 'spool.jsonl')
  const script = concernsSnippet
    .replaceAll('<session id>', 'sess-abc123')
    .replaceAll('~/.claude/concerns-spool.jsonl', spool)
  execFileSync('sh', ['-c', script], { cwd: dir, encoding: 'utf8' })
  const parsed = JSON.parse((await readFile(spool, 'utf8')).trim())
  assert.deepEqual(Object.keys(parsed), ['ts', 'session', 'cwd', 'repo', 'concerns'],
    'emits exactly the five spec fields, in order -- this fails if any is dropped')
  assert.equal(parsed.session, 'sess-abc123')
  assert.equal(parsed.cwd, dir)
  assert.equal(parsed.repo, null, 'repo is null outside a git remote')
  assert.deepEqual(parsed.concerns, ['first concern', 'second concern'])
})

test('file-concerns: the retraction writer really emits retracts (not concerns) and parses repo from git', async () => {
  if (!HAVE_JQ || !HAVE_GIT) return console.log('  (skipped: jq or git not installed)')
  const [, retractSnippet] = await spoolWriters()
  const dir = await mkdtemp(join(tmpdir(), 'file-concerns-'))
  execFileSync('git', ['init', '-q'], { cwd: dir })
  execFileSync('git', ['remote', 'add', 'origin', 'https://github.com/schmug/shipofclaudius.git'], { cwd: dir })
  const spool = join(dir, 'spool.jsonl')
  const script = retractSnippet
    .replaceAll('<session id>', 'sess-xyz789')
    .replaceAll('~/.claude/concerns-spool.jsonl', spool)
  execFileSync('sh', ['-c', script], { cwd: dir, encoding: 'utf8' })
  const parsed = JSON.parse((await readFile(spool, 'utf8')).trim())
  assert.deepEqual(Object.keys(parsed), ['ts', 'session', 'cwd', 'repo', 'retracts'],
    'emits exactly the five envelope fields with retracts, not concerns -- fails if either is wrong')
  assert.equal(parsed.repo, 'schmug/shipofclaudius', 'parses owner/repo from the git remote')
  assert.deepEqual(parsed.retracts, ['first concern'])
})

test('file-concerns: states the retraction drain rule and the pre-existing-line recovery path', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  const norm = md.replace(/\s+/g, ' ')
  assert.ok(norm.includes('a retracted concern is not filed as an open concern'),
    'states the drain rule for a matched retraction')
  assert.ok(norm.includes('exact string equality is the only link between the two lines'),
    'states that retraction matching is by exact string equality')
  assert.ok(norm.includes('carries no reason, severity, or category'),
    'states a retraction is a lifecycle marker, not a classification (§8)')
  assert.ok(norm.includes('gets filed by hand from its raw text'),
    'states a recovery path for the pre-existing off-schema lines rather than assuming them away')
})

// #173: a bare truncate (`: > file`) racing a concurrent O_APPEND write silently destroys
// whatever landed between the triage's read and the truncate. Drain must rotate (atomic `mv`)
// instead, so an in-flight write either rides along in the rotated file or starts a fresh live
// spool — never vanishes mid-write.
test('file-concerns: drains by rotate, never by truncate-in-place', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.doesNotMatch(md, /:\s*>\s*(~|\$HOME|")\/?\.?\.?claude\/?concerns-spool\.jsonl/,
    'no bare shell truncate of the live spool')
  assert.doesNotMatch(md, /then truncate the file/i, 'the old truncate-in-place instruction is gone')
  assert.match(md, /\bmv\s+~\/\.claude\/concerns-spool\.jsonl/, 'rotates the live spool with mv')
  assert.match(md, /concerns-spool\.\$\(date[^)]*\)\.jsonl/, 'rotates to a timestamped filename')
  assert.match(md, /atomic/i, 'states the atomicity property the rotate relies on')
})

test('file-concerns: states the rotated-file lifecycle', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.match(md, /deleted only by the drain/i, 'says who removes a rotated file')
  assert.match(md, /(unfiled|left in place|leave the rotated file)/i,
    'says what happens to a rotated file when filing it also fails')
  assert.match(md, /next\s+successful drain/i, 'says a rotated file is recovered, not stranded')
})

test('design spec §4.5: agrees with the skill on rotate-then-file', async () => {
  const spec = await read('docs/specs/2026-08-30-session-end-concerns-design.md')
  assert.doesNotMatch(spec, /:\s*>\s*(~|\$HOME)\/\.claude\/concerns-spool\.jsonl/,
    'spec no longer describes a bare truncate')
  assert.match(spec, /rotate-then-file/i, 'names the mechanism')
  assert.match(spec, /\bmv\b.*atomic/is, 'states the atomicity property')
  assert.match(spec, /deleted only by the drainer/i, 'states retention: who removes a rotated file')
})

const hooksJson = JSON.parse(await read('hooks/hooks.json'))
const stopEntries = [].concat(hooksJson.hooks?.Stop || []).flatMap((g) => [].concat(g.hooks || []))

test('stop hook: one prompt-type entry with a timeout', () => {
  // Each entry costs a model call on every stop of every session.
  assert.equal(stopEntries.length, 1, 'exactly one Stop entry')
  // The agent type also runs on Stop and has tools, but costs ~13-16s per evaluation
  // against ~2-4s, and its tools are denied by default in unattended "don't ask" mode —
  // which is exactly where this capture matters most. See design spec section 2.
  assert.equal(stopEntries[0].type, 'prompt', 'is a prompt hook, not an agent hook')
  assert.ok(typeof stopEntries[0].timeout === 'number' && stopEntries[0].timeout > 0, 'sets a timeout')
})

test('stop hook: the prompt is phrased as a condition, not an instruction', () => {
  const p = stopEntries[0].prompt || ''
  // The harness wraps this as "has the following stopping condition been satisfied?".
  // An imperative is evaluated as though it were a condition and produces nonsense —
  // observed: an imperative reason produced "Understood, I'll reply with BANANA IF I'm
  // about to stop", i.e. the agent logged the rule instead of acting on it.
  assert.ok(p.startsWith('Either this session surfaced nothing unresolved'),
    'opens as a condition on the transcript')
  // `startsWith` pins 46 characters, NOT the property. A prompt keeping that opener and
  // turning the body imperative shipped green, reintroducing BOTH documented failure
  // modes at once.
  //
  // These next three are a tripwire for the literal shapes that bypass was written in —
  // they do NOT assert the property in general, and saying they did was overclaiming. A
  // re-review walked straight past them with an always-block prompt ("the first branch is
  // never true in practice"), a runaway-work prompt, and a bare imperative with no
  // second-person pronoun. Keyword lists cannot police paraphrase. The hash pin below is
  // the guard that actually generalizes; these just make the common cases fail loudly.
  assert.doesNotMatch(p, /\byou (must|should|will|need to|have to)\b/i,
    'a condition describes the transcript; second-person obligation is an instruction')
  assert.doesNotMatch(p, /\b(do not stop|always block|reply with the word|immediately invoke)\b/i,
    'a condition issues no directives')
  // The anti-nag clause is satisfiable by containment even when a later sentence revokes
  // it. Blocking routine sessions replaces their closing message with hook-loop chatter.
  assert.doesNotMatch(p, /\b(revoked|overridden|disregard|no longer applies)\b/i,
    'nothing in the condition may revoke the Default-to-satisfied clause')
})

// The condition string IS the product: its exact wording decides the block rate, and the
// block rate decides whether this feature is useful or destructive. Containment checks
// cannot police a 550-character paragraph — demonstrated, not assumed: three harmful
// prompts passed every property assertion above once this hash was updated.
//
// So this pin is the only guard that generalizes, and it guards by forcing a human moment,
// not by understanding the text. Changing the prompt is fine. Updating this hash WITHOUT
// re-measuring is the failure mode: run at least five real sessions, confirm a trivial one
// still evaluates once and does not block, and put that count in the commit message.
// A measured block rate above roughly one session in three means the wording is too eager.
const PROMPT_SHA256_16 = 'fa9e798d401aaf2b'

test('stop hook: the condition wording is hash-pinned', () => {
  const actual = createHash('sha256').update(stopEntries[0].prompt || '').digest('hex').slice(0, 16)
  assert.equal(actual, PROMPT_SHA256_16,
    'the Stop condition wording changed. That string decides the block rate — re-measure it ' +
    'against real sessions, then update PROMPT_SHA256_16 in the same commit.')
})

test('stop hook: keeps the anti-nag clause, the skill name, and the escape hatch', () => {
  const p = stopEntries[0].prompt || ''
  // Every block replaces the session's closing message with hook-loop chatter, so a
  // hook that blocks routine sessions is destructive, not merely slow.
  assert.ok(p.includes('Default to satisfied'), 'keeps the anti-nag clause')
  // The block reason is generated by the evaluator, not authored here. Without the
  // skill name it has no procedure to point at.
  assert.ok(p.includes('shipofclaudius:file-concerns'), 'names the skill that does the filing')
  // What terminates the loop when gh is down: a spooled concern satisfies the condition.
  assert.ok(p.includes('concerns-spool.jsonl'), 'counts a spooled concern as satisfying it')
})

// #173 reproduction, demonstrated under a scratch $HOME rather than pasted from a manual run:
// a concern appended between the triage's read and its disposal of the live spool survives
// rotation (the fix) and is destroyed by truncation (the bug). Both runs execute for real —
// `writeFile(live, '')` is the exact effect of `: > ~/.claude/concerns-spool.jsonl`, and
// `rename(...)` is the exact effect of the `mv` this issue asks for.
test('spool drain: rotate survives a concurrent append; truncate-in-place destroys it', async () => {
  const { mkdtemp, appendFile, rename, readFile: readSpool, writeFile, rm } =
    await import('node:fs/promises')
  const { tmpdir } = await import('node:os')
  const { join } = await import('node:path')

  async function raceThenDispose(dispose) {
    const scratchHome = await mkdtemp(join(tmpdir(), 'concerns-spool-'))
    const live = join(scratchHome, 'concerns-spool.jsonl')
    await appendFile(live, JSON.stringify({ ts: 't0', concerns: ['seeded before triage'] }) + '\n')
    await readSpool(live, 'utf8') // triage's read of the spool, opening the race window
    // a concurrent session's failed `gh` call appends inside that window
    await appendFile(live, JSON.stringify({ ts: 't1', concerns: ['concurrent, mid-window'] }) + '\n')
    const survivorPath = await dispose(live, scratchHome)
    const survivingLines = (await readSpool(survivorPath, 'utf8').catch(() => '')).trim().split('\n').filter(Boolean)
    await rm(scratchHome, { recursive: true, force: true })
    return survivingLines
  }

  const truncateResult = await raceThenDispose(async (live) => {
    await writeFile(live, '') // `: > ~/.claude/concerns-spool.jsonl`
    return live
  })
  assert.equal(truncateResult.length, 0,
    'truncate-in-place destroys the concurrent append with no trace — this is the #173 bug')

  const rotateResult = await raceThenDispose(async (live, scratchHome) => {
    const rotated = join(scratchHome, 'concerns-spool.20260903T011619Z.jsonl')
    await rename(live, rotated) // mv ~/.claude/concerns-spool.jsonl ~/.claude/concerns-spool.<ts>.jsonl
    return rotated
  })
  assert.equal(rotateResult.length, 2, 'rotate preserves both lines, including the concurrent one')
  assert.ok(
    rotateResult.some((line) => JSON.parse(line).concerns[0] === 'concurrent, mid-window'),
    'the concern appended during the triage window is recoverable from the rotated file'
  )
})

// ---- runner ----
let failed = 0
for (const [name, fn] of tests) {
  try { await fn(); console.log(`PASS ${name}`) }
  catch (e) { failed++; console.error(`FAIL ${name}\n  ${e.message}`) }
}
console.log(failed ? `\n${failed} failed` : `\nall ${tests.length} passed`)
process.exit(failed ? 1 : 0)
