// Content-contract test for the session-end concern capture: the file-concerns
// process skill and the Stop hook that names it. Node built-ins only; zero token
// cost. Run: node tests/session-end-concerns.test.mjs
//
// The invariants here are the ones a well-meaning edit silently breaks. The hook
// prompt must stay phrased as a CONDITION — the harness wraps it as "has the
// following stopping condition been satisfied?", so an imperative is evaluated as
// though it were a condition and produces nonsense (observed: an imperative block
// reason produced "Understood, I'll do that IF I'm about to stop", i.e. the agent
// logged the rule instead of acting on it). It must keep its anti-nag clause,
// because every block replaces the session's closing message with hook-loop
// chatter. And it must keep naming the skill: the block `reason` is generated by
// the evaluator, not authored here, so without the name it has no procedure to
// point at.
import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'

const ROOT = new URL('../', import.meta.url)
const read = (rel) => readFile(new URL(rel, ROOT), 'utf8')

const tests = []
const test = (name, fn) => tests.push([name, fn])

test('file-concerns: exists as a process skill', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(/^---[\s\S]*?\ndescription:\s*\S.*\n[\s\S]*?---/m.test(md), 'frontmatter has a non-empty description')
  assert.ok(md.includes('name: file-concerns'), 'frontmatter name matches the directory')
  // Without this the skill is classified as a Workflow wrapper and breaks the
  // 1:1 workflow<->skill invariant in plugin-integrity.
  assert.ok(/^workflow:\s*none$/m.test(md), 'declares workflow: none (process skill, not a wrapper)')
  assert.ok(!md.includes('scriptPath'), 'must not masquerade as a Workflow wrapper')
})

test('file-concerns: files one issue per session to the agreed sink', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(md.includes('gh issue create -R schmug/agent-notes'), 'names the exact sink command')
  assert.ok(md.includes('--label concern'), 'labels the issue so triage can find it')
  assert.match(md, /one issue per session/i, 'states the one-issue-per-session rule')
  // Five issues out of one session is what the question board produced on
  // 2026-08-29 and it is the wrong shape for review.
  assert.ok(!/one issue per concern/i.test(md), 'must not file per concern')
})

test('file-concerns: never fails the turn', async () => {
  const md = await read('skills/file-concerns/SKILL.md')
  assert.ok(md.includes('~/.claude/concerns-spool.jsonl'), 'names the spool path')
  assert.match(md, /do not retry/i, 'forbids in-session retry')
  assert.match(md, /never.*(block|fail).*turn/i, 'states the never-fail-the-turn guarantee')
})

// ---- runner ----
let failed = 0
for (const [name, fn] of tests) {
  try { await fn(); console.log(`PASS ${name}`) }
  catch (e) { failed++; console.error(`FAIL ${name}\n  ${e.message}`) }
}
console.log(failed ? `\n${failed} failed` : `\nall ${tests.length} passed`)
process.exit(failed ? 1 : 0)
