// Generates the copy of this package that `.claude/workflows/factory-land.js` inlines (#262).
//
// A Workflow script cannot `import`, so factory-land carries the evaluator as source text. That
// copy is the merge authority, so it must never drift from this package. It is therefore not
// hand-maintained: it is these four modules concatenated verbatim, with `import` lines dropped and
// the `export ` keyword stripped. `tests/factory-land-sim.test.mjs` fails if the text between the
// markers differs from `renderInlineBlock()`.
//
// After editing any module below, regenerate the copy:
//   node packages/factory-gate/bin/inline.mjs --write .claude/workflows/factory-land.js

import { readFile } from 'node:fs/promises'

// Dependency order: gate-core uses all three of the others.
export const INLINED_MODULES = Object.freeze(['config.mjs', 'glob.mjs', 'extract.mjs', 'gate-core.mjs'])

export const BEGIN_MARKER = '// >>> factory-gate inline: BEGIN (generated by packages/factory-gate/bin/inline.mjs — do not edit)'
export const END_MARKER = '// <<< factory-gate inline: END'

/** One module's source as it appears in the inlined block. */
export function toInlineSource(src) {
  return String(src)
    .split('\n')
    .filter((line) => !/^import\s/.test(line))
    .map((line) => line.replace(/^export /, ''))
    .join('\n')
    .trim()
}

/** The full block that belongs between BEGIN_MARKER and END_MARKER. */
export async function renderInlineBlock() {
  const parts = []
  for (const name of INLINED_MODULES) {
    const src = await readFile(new URL(`./${name}`, import.meta.url), 'utf8')
    parts.push(`// ── ${name} ──\n${toInlineSource(src)}`)
  }
  return parts.join('\n\n')
}

/**
 * The text currently between the markers in `source`, or null when either marker is missing or
 * appears more than once.
 */
export function extractInlineBlock(source) {
  const s = String(source)
  const b = s.indexOf(BEGIN_MARKER)
  const e = s.indexOf(END_MARKER)
  if (b < 0 || e < 0 || e < b) return null
  if (s.indexOf(BEGIN_MARKER, b + 1) >= 0 || s.indexOf(END_MARKER, e + 1) >= 0) return null
  return s.slice(b + BEGIN_MARKER.length, e).replace(/^\n/, '').replace(/\n$/, '')
}

/** `source` with the text between the markers replaced by `block`. Throws when the markers are malformed. */
export function spliceInlineBlock(source, block) {
  if (extractInlineBlock(source) === null) throw new Error('inline markers missing, duplicated, or out of order')
  const s = String(source)
  const b = s.indexOf(BEGIN_MARKER) + BEGIN_MARKER.length
  const e = s.indexOf(END_MARKER)
  return `${s.slice(0, b)}\n${block}\n${s.slice(e)}`
}
